[workspace]
members = [
    "halcyon",
    "halcyon_test",
    "halcyon_dom",
    "halcyon_dom_memory",
    "halcyon_macro",
    "halcyon_macro_test",
    "examples/simple_store",
    "examples/simple_server_side_rendering",
    "examples/counter",
    "examples/simple_hello_world",
]
