[package]
name = "halcyon_macro"
version = "0.0.1"
authors = ["Richard Anaya"]
edition = "2018"
description = "The implementation of halcyon procedural macro"
license = "MIT"

[lib]
proc-macro = true
