[package]
name = "halcyon_macro"
version = "0.0.1"
authors = ["Richard Anaya"]
edition = "2018"


[lib]
proc-macro = true

[dependencies]
proc-macro-hack = "0.5"
quote = "0.6"
syn = { version = "0.15", features = ["full"] }
