[package]
name = "halcyon_macro_impl"
version = "0.0.1"
authors = ["Richard Anaya"]
edition = "2018"
description = "The implementation of halcyon procedural macro"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = "0.5"
