[package]
name = "halcyon_build_test"
version = "0.0.1"
authors = ["Richard <Richard>"]
edition = "2018"
publish = false
build = "build.rs"

[build-dependencies]
halcyon_build = { path = "../halcyon_build" }

[dependencies]
