[package]
name = "halcyon_macro_test"
version = "0.0.1"
authors = ["Richard <Richard>"]
edition = "2018"
publish = false

[dependencies]
halcyon = {path="../halcyon"}
halcyon_macro = {path="../halcyon_macro"}
halcyon_dom_memory = {path="../halcyon_dom_memory"}
