[package]
name = "halcyon_test"
version = "0.1.0"
authors = ["Richard <Richard>"]
edition = "2018"

[dependencies]
halcyon = {path="../halcyon"}
halcyon_macro = {path="../halcyon_macro"}
halcyon_dom_memory = {path="../halcyon_dom_memory"}
