[package]
name = "halcyon"
version = "0.0.1"
authors = ["Richard Anaya"]
edition = "2018"
description = "A modular virtual DOM library"
license = "MIT"

[dependencies]
halcyon_macro = {path="../halcyon_macro"}
proc-macro-hack = "0.5"
